# _config.yml
title: CyberPrivacyProtecTech
description: "Sophisticated Cyber Security Consulting Services"
baseurl: "/CyberPrivacyProtecTech"
url: "https://alexeinazarov.github.io"
lang: fr
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
google_site_verification: nugRD-c5ncylSDYGIhWEtoZjSlK3mTw1j5zR9NUO3kc
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-last-modified-at

github_username: alexeinazarov
google_analytics: G-91WCLQETXM
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
      lang: "fr"
      last_modified_at: "{{ 'now' | date: '%Y-%m-%d' }}"

include:
  - sitemap.xml

exclude:
  - assets/css
  - assets/js
  - node_modules
  - vendor

