title: CyberPrivacyProtecTech
description: "Sophisticated Cyber Security Consulting Services"
baseurl: "/CyberPrivacyProtecTech"
url: "https://alexeinazarov.github.io"
lang: fr
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
github_username: alexeinazarov
google_analytics: G-91WCLQETXM
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
      lang: "fr"
