name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write  # Ensure you have write permissions to push the changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4

    - name: Remove Gemfile.lock
      run: |
        if [ -f Gemfile.lock ]; then rm Gemfile.lock; fi

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Commit Gemfile.lock
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Gemfile.lock
        git commit -m "Regenerate Gemfile.lock"
        git push

    - name: Build site
      run: bundle exec jekyll build --verbose --trace

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

