name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4

    - name: Remove Gemfile.lock
      run: |
        if [ -f Gemfile.lock ]; then rm Gemfile.lock; fi

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Temporarily allow Gemfile.lock to be committed
      run: |
        sed -i '/Gemfile.lock/d' .gitignore

    - name: Commit changes if any
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Regenerate Gemfile.lock and update .gitignore"
          git push
        else
          echo "No changes to commit"
        fi

    - name: Restore .gitignore
      run: |
        echo "Gemfile.lock" >> .gitignore

    - name: List files after checkout
      run: |
        echo "Listing files after checkout:"
        ls -R .

    - name: Build site
      run: bundle exec jekyll build --verbose --trace

    - name: List files in _site directory
      run: |
        echo "Listing files in _site directory:"
        ls -R _site

    - name: Remove generated sitemap
      run: |
        rm -f _site/sitemap.xml

    - name: Verify and add custom sitemap
      run: |
        if [ -f custom_sitemap.xml ]; then
          echo "Custom sitemap found, touching and copying to _site directory."
          touch custom_sitemap.xml  # Update the timestamp
          cp custom_sitemap.xml _site/sitemap.xml
        else
          echo "Custom sitemap not found!"
          exit 1
        fi

    - name: List files in _site directory after adding custom sitemap
      run: |
        echo "Listing files in _site directory after adding custom sitemap:"
        ls -R _site

    - name: Verify _site directory contents before deployment
      run: |
        echo "Verifying contents of _site directory before deployment:"
        find _site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: /home/runner/work/CyberPrivacyProtecTech/CyberPrivacyProtecTech/_site
        keep_files: true

    - name: Verify sitemap on server
      run: |
        echo "Checking deployed sitemap on server:"
        curl -I https://alexeinazarov.github.io/CyberPrivacyProtecTech/sitemap.xml

    - name: Clear GitHub Pages cache
      run: |
        echo "Clearing GitHub Pages cache for sitemap:"
        curl -X PURGE https://alexeinazarov.github.io/CyberPrivacyProtecTech/sitemap.xml

    - name: Verify sitemap after cache clear
      run: |
        echo "Checking deployed sitemap on server after cache clear:"
        curl -I https://alexeinazarov.github.io/CyberPrivacyProtecTech/sitemap.xml
