name: Deploy from gh-pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Force Add and Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Deploy from gh-pages" || echo "No changes to commit"
        git push origin gh-pages
