name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write  # Ensure you have write permissions to push the changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure full repository is checked out

    - name: List files before checkout
      run: |
        echo "Listing files before checkout:"
        ls -R

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4

    - name: Remove Gemfile.lock
      run: |
        if [ -f Gemfile.lock ]; then rm Gemfile.lock; fi

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Temporarily allow Gemfile.lock to be committed
      run: |
        sed -i '/Gemfile.lock/d' .gitignore

    - name: Commit changes if any
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Regenerate Gemfile.lock and update .gitignore"
          git push
        else
          echo "No changes to commit"
        fi

    - name: Restore .gitignore
      run: |
        echo "Gemfile.lock" >> .gitignore

    - name: List files after checkout
      run: |
        echo "Listing files after checkout:"
        ls -R

    - name: Build site
      run: bundle exec jekyll build --verbose --trace

    - name: List files in _site directory
      run: |
        echo "Listing files in _site directory:"
        ls -R _site

    - name: Remove generated sitemap
      run: |
        rm -f _site/sitemap.xml

    - name: Add custom sitemap
      run: |
        cp custumsitemap.xml _site/sitemap.xml

    - name: List files in _site directory after adding custom sitemap
      run: |
        echo "Listing files in _site directory after adding custom sitemap:"
        ls -R _site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Clear GitHub Pages cache
      run: |
        curl -X PURGE https://alexeinazarov.github.io/CyberPrivacyProtecTech/sitemap.xml

